version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # Check for updates once a week
      interval: "weekly"
    # Raise pull requests for version updates against the `development` branch
    target-branch: "development"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"